---

- name: Add the Erlang public GPG key to the apt repo
  apt_key: url=http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
           state=present

- name: Add Erlang to the sources list
  apt_repository: repo='deb http://packages.erlang-solutions.com/ubuntu precise contrib'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install Erlang
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - erlang
    - erlang-nox
